backend:
  name: git-gateway
  branch: main  # 内容存储的分支
media_folder: "static/uploads"  # 上传文件的存储路径
public_folder: "/uploads"       # Hugo 中引用的公开路径
publish_mode: editorial_workflow  # 启用草稿工作流

collections:
  - name: "posts"
    label: "文章"
    folder: "content/posts"
    create: true
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime" }
      - { label: "正文", name: "body", widget: "markdown" }
      - { label: "PDF 文件", name: "pdf", widget: "file", required: false } # 添加 PDF 上传字段  
      - { label: "Excel文件", name: excel_file, widget: "file", allowed_extensions: ["xlsx", "xls"], required: false } # 添加 Excel 上传字段
      - { label: "APK文件", name: apk_file, widget: "file", allowed_extensions: ["apk"], required: false } # 添加 APK 上传字段